name: custom-environment-variables

on: [push]


# Here the environment variable is declared in workflow level
env:
    PUBLICENV: Available for all jobs in this workflow

jobs:
 
    Bash-Checking:
       runs-on: windows-2019
       steps:
         - name: Print
           run: | 
               pwd
               git --version
           shell: bash   
       
       
    WorkFlow_Level_Variables:
        runs-on: ubuntu-latest
        steps:
            - name: workFlow-variable
              run: echo "$PUBLICENV"
            
    
    Job_Level_Variables:
        # Here the environment variable is declared in Job level
        env:
            JOBENV: Available for this specific job only
        runs-on: ubuntu-latest
        steps:
            - name: Job-Variable
              run: echo "$JOBENV"


    Step_Level_Variables:
         runs-on: ubuntu-latest
         steps:
            - name: step-variables
              # Here the environment variable is declared in step level
              env:
                  STEPENV: Available for this specific job only
              run: echo "$STEPENV"  

            - name: step-2
              run: echo "$STEPENV"
