name: default-environment-variables

on: [push]


jobs:
  version_job:
         runs-on: ubuntu-latest
         steps:
         - name: Create version number
           run: echo "::set-output name=version_number::1.2.3"
           id: version_step

  output:
        needs: version_job
        runs-on: windows-2019
        steps:
          - name: Output
            run: echo "${{ jobs.version_job.steps.version_step.outputs.version_number }}"

           
#      sample-job2:
#       runs-on: windows-2019
#       steps:
#         - name: echo-default-env-variables
#           shell: cmd
#           run: |
#               echo "GITHUB_RUN_NUMBER:" $GITHUB_RUN_NUMBER
#                   echo ${{RUN}}             
                  
                  
                  
#      sample-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: echo-default-env-variables
#               run: |
#                   echo "Home: ${HOME}"
#                   echo "GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"
#                   echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
#                   echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
#                   echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
#                   echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
#                   echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
#                   echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
#                   echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
#                   echo "GITHUB_SHA: ${GITHUB_SHA}"
#                   echo "GITHUB_REF: ${GITHUB_REF}"
