name: Events_and_Activity_Types

#Events
# on: [push, pull_request]

# on:
#   push:
#    branches:
#       - master
#       - main


on:
 pull_request:
   types:
      - opened
      - closed
   branches:
       - main
       - master

# on:
#   schedule:
#     - cron: "1 * * * * *"
      # - cron: "0/5 * * * * *"



jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "Hello_World"

