name: expressions

on:
  [push]


env:
  addition : ${{2+2}}
  myNull: ${{ null }}
  myBoolean: ${{ false }}
  myIntegerNumber: ${{ 711 }}
  myFloatNumber: ${{ -9.2 }}
  myHexNumber: ${{ 0xff }}
  myExponentialNumber: ${{ -2.99-e2 }}
  myString: ${{ 'Mona the Octocat' }}
  myEscapedString: ${{ 'It''s open source!' }}

jobs:

  Testing:
    runs-on: ubuntu-latest
    steps:
       - name: Print expressions
         run: |
          echo  ${{TEST}}
         env:
           TEST: ${{ 2 + 2}} 
      
