# https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event
# Make an api call to trigger this workflow
# https://api.github.com/repos/saiteja8848/GitHub_Actions_Learning/dispatches

  #  Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
  #   Accept: `application/vnd.github.v3+json`,
  #   Content-Type: `application/json`,
  #   {'event_type': 'build' , "client_payload": {"env":{"buildId":"wuglibs"}}}

# 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


name: Repository_Dispatch

on:
 repository_dispatch:
   types: [build]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Print Payload
        env:
          STRATEGY_CONTEXT: ${{ toJSON(github.event.client_payload) }}
        run: echo "$STRATEGY_CONTEXT.buildId"
 
