# https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event

name: Repository_Dispatch

on:
 repository_dispatch:
   types: [Set_Environment_Variables]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Print Payload
        run: echo ${{github.event.client_payload.env}}

