name: Output

on: [push]

jobs:
    Input-Output:
      runs-on: ubuntu-latest
      steps:
        - name: Simple JS Action
          id: greet 
          uses: actions/hello-world-javascript-action@v1
          with: 
            who-to-greet: John
        
        - name: Log Greeting Time
          run: echo "${{ steps.greet.outputs.time }}"

        - name: Set selected color
          run: echo '::set-output name=SELECTED_COLOR::green'
          id: random-color-generator

        - name: Get color
          run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
       
          
        - name: Create issue using REST API
          run: |
            curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "title": "Automated issue for commit: ${{ github.sha }}",
              "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
              }'  

