name: Powershell-scripts

on: [push]



jobs:
 
    ExecutePowershellScript:
       runs-on: windows-2019
       steps:
         - name: run
           shell: powershell
           run: >
              Function Test($param){
                 write-host $param;
                 write-host $param;
              };
              Test $env:PATH_ConstantsFile;
           env:
             param: "hello"
             PATH_ConstantsFile: "$GITHUB_WORKSPACE\\Script Files\\Constants.h"
              
