name: Test

on: [push]

env:
  RELEASETYPE: daily


jobs:
  SetupEnvironmentVariables:
    runs-on: windows-2019
    steps:
      - name: Run tests
        run: |
          echo env.RELEASETYPE
          echo "::set-output name=BuildDescription::''"
          echo "::set-output name=MARKETINGVERSION::Rocket.0.0"
          echo "::set-output name=RELEASESUFFIX::Daily"
          echo "::set-output name=FNCServerURL::http://atlflexera01.servers.ipswitch.com"
          echo "::set-output name=FNCVersion::${PRODUCT_VERSION}_${RELEASESUFFIX}"
          echo "::set-output name=OUTPUTEXENAME::${PROJECT_NAME}-${RELEASESUFFIX}.exe"
         
  


  
      
