name: Example - Share output between jobs

on:
  push:

env:
  RELEASETYPE: 'daily'


jobs:
  produce:
    runs-on: windows-2019
    outputs:
      myValue: ${{ steps.exposeValue.outputs.myvalue }}
    steps:
      - name: Create value as an environment variable
        if: env.RELEASETYPE == 'daily'
        shell: cmd
        run: |
          echo "MY_VALUE='MYVALUE1'" >> $GITHUB_ENV
        
      - name: Create
        if: env.RELEASETYPE == 'beta'
        shell: cmd
        run: |
          echo "MY_VALUE='MYVALUE2'" >> $GITHUB_ENV
          
          
      - name: Expose value 
        id: exposeValue
        shell: cmd
        run: |
          echo "::set-output name=myvalue::${{ env.MY_VALUE }}"
            
  consume:
    runs-on: windows-2019
    needs: produce 
    steps:
      - name: Use value
        shell: cmd
        run: |
          echo "${{ needs.produce.outputs.myvalue }}"
