name: Example - Share output between jobs Testing

on:
  push:

env:
  RELEASETYPE: 'daily'


jobs:
  produce:

    runs-on: windows-2019
    
    outputs:
      myValue: ${{ steps.exposeValue.outputs.myvalue }}

    steps:
     
      - name: Create value as an environment variable
        shell: cmd
        run: |
          echo "MY_VALUE='MYVALUE'" >> $GITHUB_ENV
          
      - name: Expose value 
        id: exposeValue
        run: |
          echo "::set-output name=myvalue::${{ env.MY_VALUE }}"
            
  consume:

    runs-on: windows-2019

    needs: produce
    
    steps:
      
      - name: Use value
        shell: cmd
        run: |
          echo "${{ needs.produce.outputs.myvalue }}"
 
  
