name: my pipeline

on:
    push:
env:
  REL: daily

jobs:
    job1:
      runs-on: windows-2019

      outputs:
        releaseSuffix: ${{ steps.step1.outputs.RELEASESUFFIX }}
   
      steps:
        - id: step1
          shell: cmd
          run: |  
              if %REL% == 'daily' (
                 echo "::set-output name=RELEASESUFFIX::Daily"
              )
              if %REL% == 'beta'(
                echo "::set-output name=RELEASESUFFIX::Beta"
              )

    job2:
      runs-on: windows-2019
      needs: job1
      steps:
        - run: echo ${{ needs.job1.outputs.releaseSuffix }} 
