name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # test 1
    - name: Read first property
      id: read_first_property
      uses: ./
      with:
        path: './test/foo.properties'
        property: 'foo'
    - name: Do something with the property value
      run: echo ${{ steps.read_first_property.outputs.value }}
    - name: Verify first property has been read correctly
      if: steps.read_first_property.outputs.value != 'bar'
      run: exit 1

    # test 2
    - name: Read third property
      id: read_third_property
      uses: ./
      with:
        path: './test/foo.properties'
        property: 'foo.bar.foo'
    - name: Verify third property has been read correctly
      if: steps.read_third_property.outputs.value != 'foo bar'
      run: exit 1

      # test 3
    - name: Read second property
      id: read_second_property
      uses: ./
      with:
        path: './test/foo.properties'
        property: 'foo.bar'
    - name: Verify second property has been read correctly
      if: steps.read_second_property.outputs.value != 'foobar'
      run: exit 1

    # test 4: properties with spaces around the equals sign.
    - name: Read property with spaces
      id: read_property_with_spaces
      uses: ./
      with:
        path: './test/foo.properties'
        property: 'with.space'
    - name: Verify property with spaces has been read correctly
      if: steps.read_property_with_spaces.outputs.value != '42'
      run: exit 1
