name: my pipeline

on:
    workflow_dispatch:
        inputs:  
            device:
                description: '[1] iPhone, [2] Samsung Galaxy'
                required: true
                default: '1'

jobs:
  test:
    runs-on: windows-2019
    steps:
        - name: Set device
          id: setDevice
          run: |
            if [[ "${{ github.event.inputs.device }}" == "1" ]]; then
                echo "::set-output name=deviceString::iPhone"
            fi
            if [[ "${{ github.event.inputs.device }}" == "2" ]]; then
                echo "::set-output name=deviceString::Samsung Galaxy"
            fi
