name: Test

on: [push]




jobs:
 
  SetupEnvironmentVariables:
    runs-on: windows-2019
    steps:
      - name: Run tests
        shell: cmd
        env: 
          RELEASETYPE : 'daily'
        run: |
          if %RELEASETYPE% == 'daily'; then
            echo "flag=daily" >> GITHUB_ENV
          else if %RELEASETYPE% == 'beta'; then
            echo "flag=beta" >> GITHUB_ENV 
          else
            echo "flag=er" >> GITHUB_ENV 
          fi 
  
      - name: Print
        run: echo env.flag

  
      
